#pragma once 
//indecses for events
#define PreFactionTurnStartNumCode 0//!
#define FactionTurnStartCode 1//!
#define FactionTurnEndCode 2//!
#define FactionNewCapitalCode 3//!
#define FactionWarDeclaredCode 4//!
#define FactionAllianceDeclaredCode 5//!
#define FactionTradeAgreementMadeCode 6//!!
#define FactionBreakAllianceCode 7//
//#define InterFactionMarriageCode 8
#define GiveMoneyCode 9//!
#define HordeFormedCode 10//!
#define TransgressionCode 11//!
//#define DishonestTransgressionCode 12
#define UpdateAttitudeCode 13//!
#define DemeanourCode 14//!
#define CharacterSelectedCode 15//!
#define GeneralAssaultsResidenceCode 16//!!
#define GeneralAssaultsGeneralCode 17//!!
#define GeneralCaptureResidenceCode 18//!!
#define GeneralCaptureSettlementCode 19//!
#define SiegeEquipmentCompletedCode 20//!
#define PostBattleCode 21//!
#define SettlementSelectedCode 22//!
#define SettlementUpgradedCode 23//!
#define SettlementConvertedCode 24//!
//#define InsurrectionCode 25
#define CityRiotsCode 26//!
#define GiveSettlementCode 27//!
//#define CityRebelsCode 28
#define UngarrisonedSettlementCode 29//!
#define OccupySettlementCode 30//!
#define SackSettlementCode 31//!
#define ExterminatePopulationCode 32//!
//#define CitySackedCode 33
#define BuildingCompletedCode 34//!
#define BuildingDestroyedCode 35//!
#define AddedToBuildingQueueCode 36//!
#define GuildUpgradedCode 37
#define GuildDestroyedCode 38
#define AgentCreatedCode 39//!
#define UnitTrainedCode 40//!
#define UnitDisbandedCode 41//!
#define AddedToTrainingQueueCode 42//!
#define EventCounterCode 43//!
#define TileSeenCode 44//
#define ObjSeenCode 45//!
#define CharacterPanelOpenCode 46//!
#define SettlementPanelOpenCode 47//!
#define FinancesPanelOpenCode 48//!
#define FactionSummaryPanelOpenCode 49//!
#define FamilyTreePanelOpenCode 50//!
#define DiplomaticStandingPanelOpenCode 51//!
#define DiplomacyPanelOpenCode 52//!
#define PreBattlePanelOpenCode 53//!
//#define RecruitmentPanelOpenCode 54
//#define ConstructionPanelOpenCode 55
#define TradePanelOpenCode 56//!
//#define HireMercenariesPanelOpenCode 57
#define NavalAutoResolvePanelOpenCode 58//!
#define IncomingMessageCode 59//!
#define MessageOpenCode 60//!
#define MessageClosedCode 61//!
#define RequestBuildingAdviceCode 62//!
#define RequestTrainingAdviceCode 63//!
//#define RequestMercenariesAdviceCode 64
#define ButtonPressedCode 65//!
#define UIElementVisibleCode 66//!
#define ScrollOpenedCode 67//!
#define ScrollClosedCode 68//!
//#define AdviceSupressedCode 69
#define ScrollAdviceRequestedCode 70//!
#define PreBattleScrollAdviceRequestedCode 71//!
#define NavalPreBattleScrollAdviceRequestedCode 72//!
#define SettlementScrollAdviceRequestedCode 73//!
//#define AbandonShowMeCode 74
//#define ScriptedAdviceCode 75
#define GameReloadedCode 76//!
//#define DeclineAuatedSettlementManagementCode 77
#define DisasterCode 78//!
#define PopeElectedCode 70//!
#define VotedForPopeCode 80//!
#define FactionExcommunicatedCode 81//!
#define CrusadeCalledCode 82//!
#define CrusadeEndsCode 83//!
#define PopeAcceptsCrusadeTargetCode 84//!
#define PopeRejectsCrusadeTargetCode 85//!
#define UnitsDesertCrusadeCode 86//!
#define ArmyTakesCrusadeTargetCode 87//!
//#define ForgivenessCode 88
#define InquisitorAppointedCode 89//!
#define AssassinCaughtAttackingPopeCode 90//!
#define CollegeOfCardinalsPanelOpenCode 91//!
#define MultiTurnMoveCode 92//!
#define UngarrisonedFortCode 93//!
