style='./EOP-Theme'
dir='./generatedLuaImGuiDocs'
file = {'../M2TWEOP-luaPlugin/luaPlugin/imgui/sol_ImGui.h'}
merge=true
format ='markdown'
project = 'EOP Lua Plugin'
description='M2TW Engine Overhaul Project is designed to expand the capabilities of the game Medieval 2: Total War.'
kind_names={topic='Extra',module='Modules'}
one=true
title='M2TWEOP ImGui Documentation'
use_markdown_titles=true
not_luadoc=true