style='./EOP-Theme'
dir='./generatedLuaDocs'
file = {'../M2TWEOP-luaPlugin/luaPlugin/luaP.cpp','../M2TWEOP-luaPlugin/luaPlugin/luaEopEdu.cpp','../M2TWEOP-luaPlugin/luaPlugin/luaP2.cpp','../M2TWEOP-luaPlugin/luaPlugin/luaEvents.cpp','../M2TWEOP-luaPlugin/luaPlugin/luaFbx.cpp','../M2TWEOP-luaPlugin/luaPlugin/luaSounds.cpp'}
merge=true
format ='markdown'
project = 'M2TWEOP\nscripting'
description='Project, created to expand M2TW engine'
kind_names={topic='Extra',module='Modules'}
one=true
title='M2TW Engine Overhaul Project'
use_markdown_titles=true
not_luadoc=true
readme = {'./README_IMGUI.md'}